---
deployment:
  tasks:
    - export DEPLOYMENT_TARGET=/home/flik/public_html/flikserver
    - /bin/cp -R . $DEPLOYMENT_TARGET
    - cd $DEPLOYMENT_TARGET
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run start
    - /usr/local/bin/pm2 restart all
